### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by BIGEAZY289** [LagradOst/CloudStream-2#4] opened 2020-07-10 17:07 UTC
Crashing in redmi note 4

**Comment by LagradOst** [comment] 2020-07-10 18:51
Have you tried reinstalling the app? Does it crash instantly or after 2 sec? Do it crash after you do something?

**Comment by BIGEAZY289** [comment] 2020-07-11 02:50
No it crashes after 2 seconds I tried to reinstall but same result

**Comment by LagradOst** [comment] 2020-07-12 11:34
I think I have discovered the error, but I am not quite sure that it is the same as your issue. The app crashed when loading recomendations for me, but only from bookmarks (related), so having top 100 disabled or turning the internet off before starting the app should avoid the crash. In the next update this issue will be fixed, but I want to know if this is the casue of your app crashing or if it is something else.

**Comment by BIGEAZY289** [comment] 2020-07-12 15:39
No it's different when I install the app it waits for some seconds and then crash then when I try to open it for the second time it crash instantly I tried it after reinstalling but same result so can u fix this in your next update?

**Comment by BIGEAZY289** [comment] 2020-07-12 15:40
Maybe it only happens in my device modles idk

**Comment by LagradOst** [comment] 2020-07-12 15:59
If you turn of your internet does it crash?

**Comment by BIGEAZY289** [comment] 2020-07-13 04:10
Yeah it does😞

**Comment by LagradOst** [comment] 2020-07-13 08:25
Shit, then I need to investigate more into what could have cause it. Im currently patching against any possible cause, it might be that the app dosent have storage permission, but it would not cause it to crash instantly.

**Comment by BIGEAZY289** [comment] 2020-07-13 08:32
How can I give storage permission if its going to crash like gokus  ultra istinct(anime reference)😂😂

**Comment by LagradOst** [comment] 2020-07-13 08:39
under settings > apps > cloudstream 2 > premissions > storage

**Comment by BIGEAZY289** [comment] 2020-07-13 13:30
Already tried it at first nothing happened

**Comment by LagradOst** [comment] 2020-07-13 14:13
try the latest update, see if that fixes anything

**Comment by BIGEAZY289** [comment] 2020-07-13 16:45
Nah still the same😞

**Comment by LagradOst** [comment] 2020-07-13 18:10
ok, this is a super basic version of cloudstream, I tried just removing a lot of suff. Do this crash instantly? https://drive.google.com/file/d/1kcY4PPup9niD29yFUto--F2j6rcFqvHA/view?usp=sharing

**Comment by BIGEAZY289** [comment] 2020-07-14 01:05
Yeah it's qorking but top 100 us not working

**Comment by BIGEAZY289** [comment] 2020-07-14 01:08
Will u be able to provide some hd links provider like good quality in app it shows 720p but not really the one so pls add some good providers

**Comment by LagradOst** [comment] 2020-07-14 01:14
the app I sent was just a test to see what caused the crash. If you have any good hd site, then I can add it. The problem is finding a good providers without captcha.

**Comment by BIGEAZY289** [comment] 2020-07-14 01:15
Why I try to download substitle it freezes(stop's responding) ans everything takes 10seconds to open even my network is good

**Comment by LagradOst** [comment] 2020-07-14 01:15
I am currently working on a real fix to your crashing.

**Comment by LagradOst** [comment] 2020-07-14 01:18
That is probably because you are running a very basic version that dosent include android native features beacuse debugging. I will send a fix soon

**Comment by BIGEAZY289** [comment] 2020-07-14 01:29
Yeah there are many fix which need to be done can't play in external players

**Comment by BIGEAZY289** [comment] 2020-07-14 01:30
Thnx brother ur awesome😎

**Comment by BIGEAZY289** [comment] 2020-07-14 12:31
When can I expect it (update)

**Comment by LagradOst** [comment] 2020-07-14 15:42
try https://drive.google.com/file/d/1fB_AJQn1IZ2akXsn0UiCQ5MkoOP2V2JP/view this is a debug version and will show toast as debug info. If you get any toast when starting the app, please tell me what popped up so I can fix it. If this version dosent crash on your phone then I will post this version as a real update.

**Comment by BIGEAZY289** [comment] 2020-07-14 16:22
Some command like box popping up everytime

**Comment by BIGEAZY289** [comment] 2020-07-14 16:22
And many sources not working at all add some good sources pls if u want I can recommend u some

**Comment by BIGEAZY289** [comment] 2020-07-14 16:25
Some fatal error command box popping everytime

**Comment by LagradOst** [comment] 2020-07-14 16:52
1. "And many sources not working at all add some good sources pls if u want I can recommend u some" That is because of android cert update, the sources are not bad, you can download it or play it in the browser 9/10 times. The player I use is based in VLC and they have not updated this. 
2. "Some command like box popping up everytime" this is just a debug version, but I want to know, is the app is not crashing anymore?
3. If you have any good sites just post them here and I will probably add it

**Comment by BIGEAZY289** [comment] 2020-07-15 00:09
No app is not crashing anymore

**Comment by BIGEAZY289** [comment] 2020-07-15 00:10
Just that pop up is annoying that's all

**Comment by LagradOst** [comment] 2020-07-15 00:54
Published an update, if you feel like the problem is solved then you can close the issue.

**Comment by BIGEAZY289** [comment] 2020-07-15 02:32
In internal player videos are not playing

**Comment by BIGEAZY289** [comment] 2020-07-15 02:33
And when I play it in vlc it's plays well but after sometime it push me back to the app

**Comment by BIGEAZY289** [comment] 2020-07-15 02:47
It only happens when I try to download substitle in vlc

**Closed** 2020-07-15 10:34 UTC
Labels: bug
