### ISSUE TITLE
[Idea] CloudSync

### ISSUE THREAD

**Issue by snisnik** [LagradOst/CloudStream-2#10] opened 2020-07-15 18:03 UTC
Maybe is a good feature to have a simple clpud sync to save viewed shows and settings.
Maybe firebase or even a simple spreadsheet. To save user/password and a json with the settings.
And in the app nothing to complex.. a modal popup  to login and register, register just inser a new user.
I don't know what you think.

**Comment by LagradOst** [comment] 2020-07-15 19:43
A centrilized server with accounts, that is a good idea, and not so hard to make. The problem is that I dont have a server to host it on. I could do export/import settings, or some networks sync to send data from one phone to another, but a server will be hard. I could post the data on a public js data site, and then link the account with and id to your account if you want that. It will achive the same thing, but I can not insure that the site will keep running forever. Do you run it on two phones or just want to back up data?

So what do you want if I would implement this feature:
1. Make a c# server that ppl can host on their own computer/linux server and log in to in app
2. Export and Import settings as a .txt file
3. Send data from phone to phone over network (both of them must be in app at the same time)
4. Store data on a public js site, and linking account with and ID and password (the data will be encrypted on the site)

**Comment by snisnik** [comment] 2020-07-15 19:56
I  think it can be usefull for both... backup and sync with different devices.
I tought about the server, thats why i mention it might be doable using firebase or just a simple google spreadsheet, where you have the user in column A, pin in column B and in column C a json with all the data..
But i don't know how much complexity does it add.

**Comment by LagradOst** [comment] 2020-07-15 19:59
So option 1 and 2? I can store the data in a simple txt file it is just a matter of transfering the data.

**Comment by snisnik** [comment] 2020-07-15 20:01
Yes...option 1 and2 witll work..
Maybe i can leter even use my old raspberry as the serverfor my entire famility hehe

**Comment by LagradOst** [comment] 2020-07-15 21:01
What do you want synced? watched episodes, settings, cached data? Do you need the server to be globaly accessible or local network?

**Comment by snisnik** [comment] 2020-07-15 21:27
The most important thing is the watched episodes i think.. and globally accedes would be awsome!

**Comment by LagradOst** [comment] 2020-07-16 01:36
Added option 2

**Comment by LagradOst** [comment] 2020-07-18 20:47
Most of the code for the server is done on a private repo, the problem is that 256 block size is an invalid operation on .net core, I dont know if I can port it to linux :/ I will see what I can do.

**Comment by LagradOst** [comment] 2020-07-20 18:41
As of now, the login will just be a one time thing in the settings, then opeing the app it will fetch data, and when closing the app it will post the data. The login will require 3 thing, 1: site url, 2: unique username, 3: password. IT WILL overide bookmarks, viewhistory, viewtime when fetched, so offline edit will be overwritten. The password will be stored in plain text on the client, but not on the server.

All data sent to the server will be encrypted clientside via password, the password and username will be hashed when send and data will be sent via a get request with password, username and data via headers. The first time you create the account the hashed password will be sent, but further requests will be via a encrypted one time password based on the hashed password + time.

**Comment by snisnik** [comment] 2020-07-20 19:26
Wow! you are a genius!!
Maybe a nice addition for the future, maybe a parameter in the text file to enable disable acces (to prevent the gounded kids from using it)

**Comment by LagradOst** [comment] 2020-07-20 23:41
Do you want login like netflix with multi accounts from just one login or separate accounts you have to log into for eatch user? also how would lock work?

**Comment by snisnik** [comment] 2020-07-21 02:21
It was just an idea that came to my mind when I was typing...in my mind was like super simple..one user/password one account..
And I think something simple a dialog over the app for the login..

**Comment by LagradOst** [comment] 2020-07-21 13:15
this is the login, found in settings: https://cdn.discordapp.com/attachments/551382684560261121/735122337111867473/Screenshot_20200721_151306_com.CloudStreamForms.CloudStreamForms.jpg

**Comment by snisnik** [comment] 2020-07-21 17:39
Exactly! simple as that is what i was imagining and it checks with the server if the user is active or not to allow use the app or not

**Comment by LagradOst** [comment] 2020-07-26 14:16
Will publish an update now, it will not include the server. The code is done, but I have not tested it yet on a real ip, so I cant publish that part now. (Import and Export data is in the update, Export data ~12kb, Export Everything ~500kb)

**Comment by santiagoworkana** [comment] 2020-07-27 12:37
Great! let me know if i can help somehow with the server testing.

**Comment by LagradOst** [comment] 2020-07-31 22:00
Testing CloudSync via server rn, might be in the next update along with twist.moe

**Comment by santiagoworkana** [comment] 2020-08-03 13:24
Awsome!

**Comment by LagradOst** [comment] 2020-08-03 13:58
You can the server here https://github.com/LagradOst/CloudStreamAccountServer/releases/ but I have not yet published the app update

**Comment by LagradOst** [comment] 2020-08-05 23:16
Just published the update now. You can close this issue if you feel like it is fixed after trying it for yourself. It should work, but I have only done minor testing on it.

**Comment by santiagoworkana** [comment] 2020-08-10 12:28
I'll give a few tests this week 👍

**Comment by LagradOst** [comment] 2020-08-31 18:23
"21 days ago" im closing this issue, assuming it is solved. If you experience any bugs in the account server post it in https://github.com/LagradOst/CloudStreamAccountServer/ issues.

**Closed** 2020-08-31 18:23 UTC
Labels: enhancement
